language: python
cache: pip
cache:
  directories:
    - $HOME/python-debug
    - $HOME/.pyenv/versions
    - $HOME/Library/Caches/pip

env: PYTHON_DEBUG_BUILD=0

matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "3.6"
      env:
        - PYTHON_DEBUG_BUILD=1
        - PYTHONDIR=~/python-debug/
    - os: linux
      dist: xenial
      python: "3.7"
    - os: linux
      dist: xenial
      python: "3.8-dev"
      env:
        - PYTHONDIR=/opt/python/3.8-dev/
        # For reasons I do not begin to understand, python-config is
        # leaving this off on travis.
#        - LDFLAGS=-lpython3.8
        - LDFLAGS=-L/opt/python/3.8-dev/lib
    - os: osx
      osx_image: xcode8.3
      language: generic
      env: PYTHONVERSION=3.6.3

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export PYTHONVERSION=`python --version | awk '{ print $2 }'`

    # We need to find where the py
    export PYTHONDIR=${PYTHONDIR-"/opt/python/$PYTHONVERSION"}

    if [[ $PYTHON_DEBUG_BUILD == 1 ]]; then
      VENV=$PYTHONDIR/env
      scripts/build-debug-python.sh $PYTHONVERSION $PYTHONDIR $VENV
      source $VENV/bin/activate
    fi
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # Attempt to install, skipping if version already exists.
    pyenv install $PYTHONVERSION -s
    # Regenerate shims
    pyenv rehash
    # Manually set pyenv variables per https://pythonhosted.org/CodeChat/.travis.yml.html
    export PYENV_VERSION=$PYTHONVERSION
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
  fi

  # Check python install
  which python
  python --version

  # Upgrade pip, setuptools, and wheel
  pip install -U pip setuptools wheel

install:
  - pip install -r mypyc/external/mypy/test-requirements.txt

script: |
  set -e
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export PYTHONCONFIG="$PYTHONDIR/bin/python-config"
#    export PYTHONCONFIG="$PYTHONDIR/bin/python3-config"
    export PYTHONCONFIG="python-config"
    #export PYTHONCONFIG="python-config"
    python-config --prefix
    python-config --ldflags
    python3-config --ldflags
    $PYTHONDIR/bin/python-config --ldflags
    which python-config
    export LD_LIBRARY_PATH="$PYTHONDIR/lib"
    if [[ $PYTHON_DEBUG_BUILD != 1 ]]; then
      pytest -n4 mypyc/test/test_external.py -k 'not test_self_type_check'
    fi
    if [[ $PYTHON_DEBUG_BUILD == 1 ]]; then
      pytest -n4 mypyc/test/test_run.py mypyc/test/test_external.py -k 'not test_self_type_check'
    fi
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pytest -n4 mypyc
  fi
